import { createHash, timingSafeEqual } from 'node:crypto'

/**
 * Constant-time shared-secret comparison.
 *
 * Both sides are hashed to a fixed 32 bytes before comparison. A naive
 * `a.length !== b.length` guard returns faster for wrong-length inputs, which
 * leaks the secret's length to anyone able to sample a public endpoint enough
 * times to measure it. Hashing first removes the length branch entirely, so
 * every comparison costs the same regardless of input.
 */
export function secretMatches(provided: string | null | undefined, expected: string): boolean {
  if (!provided) return false

  const a = createHash('sha256').update(provided).digest()
  const b = createHash('sha256').update(expected).digest()

  return timingSafeEqual(a, b)
}

/**
 * Slugs are generated by `slugify(x, { lower: true, strict: true })` during
 * migration, and authored slugs are expected to match. Contentful puts no
 * validation on the field, so anything read from an entry or a query param is
 * untrusted until checked here.
 *
 * This matters most before a redirect: a slug of `//attacker.tld` would build
 * the path `///attacker.tld`, which browsers resolve as a protocol-relative
 * external URL.
 */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export function isValidSlug(slug: string): boolean {
  return slug.length > 0 && slug.length <= 256 && SLUG_PATTERN.test(slug)
}
